gui:
  spinner:
    frames:
      - "⣾"
      - "⣽"
      - "⣻"
      - "⢿"
      - "⡿"
      - "⣟"
      - "⣯"
      - "⣷"
    rate: 50
os:
  edit: "code {{filename}}"
customCommands:
  - key: "L"
    prompts:
      - type: "input"
        title: "Commit"
        initialValue: ""
    command: git commit -m "{{index .PromptResponses 0}}" --no-verify
    context: "g"
    subprocess: true
